### ISSUE TITLE
Error???

### ISSUE THREAD

**Issue by wolfetrucking** [mscrivo/OotD#134]
Sorry, I am far from an IT....i changed my office 365 version from 64 bit to 32 bit, OOD would not work, i uninstalled and re installed and OOD still wont work...

2019-09-05 00:00:00.7379 WARN Unable to go to today on calendar. COMException System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at OLXLib.IViewCtl.GoToToday()
   at OotD.Forms.MainForm.UpdateTimer_Tick(Object sender, EventArgs e) Void GoToToday()    at OLXLib.IViewCtl.GoToToday()
   at OotD.Forms.MainForm.UpdateTimer_Tick(Object sender, EventArgs e)
2019-09-05 06:57:26.8320 INFO Command Line Args:  
2019-09-05 06:57:26.8633 INFO Found 15.0 key 
2019-09-05 06:57:26.8633 INFO Found 16.0 key 
2019-09-05 06:57:26.8633 INFO Found ClickToRun key 
2019-09-05 06:57:26.8633 INFO Found Common key 
2019-09-05 06:57:26.8633 INFO Found Delivery key 
2019-09-05 06:57:26.8633 INFO Found Outlook key 
2019-09-05 06:57:26.8633 INFO Office version 16 detected 
2019-09-05 06:57:26.8633 INFO Outlook path reported as C:\Program Files\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2019-09-05 06:57:26.8633 INFO Outlook Bitness is: x64 
2019-09-05 06:57:27.5350 DEBUG Checking to see if there is an instance running. 
2019-09-05 06:57:27.5662 WARN Instance is already running, exiting. 
2019-09-05 06:58:13.7261 INFO Command Line Args:  
2019-09-05 06:58:13.7730 INFO Found 15.0 key 
2019-09-05 06:58:13.7730 INFO Found 16.0 key 
2019-09-05 06:58:13.7730 INFO Found ClickToRun key 
2019-09-05 06:58:13.7730 INFO Found Common key 
2019-09-05 06:58:13.7730 INFO Found Delivery key 
2019-09-05 06:58:13.7730 INFO Found Outlook key 
2019-09-05 06:58:13.7730 INFO Office version 16 detected 
2019-09-05 06:58:13.7730 INFO Outlook path reported as C:\Program Files\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2019-09-05 06:58:13.7730 INFO Outlook Bitness is: x64 
2019-09-05 06:58:14.0385 DEBUG Checking to see if there is an instance running. 
2019-09-05 06:58:14.4447 INFO Starting the instance manager and loading instances. 
2019-09-05 06:58:14.5228 DEBUG Loading app settings from registry 
2019-09-05 06:58:14.5228 DEBUG Settings Found. 
2019-09-05 06:58:14.7259 INFO Outlook folder path: IPM.Appointment 
2019-09-05 08:21:14.4074 INFO Command Line Args:  
2019-09-05 08:21:14.4698 INFO Found 15.0 key 
2019-09-05 08:21:14.4698 INFO Found 16.0 key 
2019-09-05 08:21:14.4698 INFO Found ClickToRun key 
2019-09-05 08:21:14.4698 INFO Found Common key 
2019-09-05 08:21:14.4698 INFO Found Delivery key 
2019-09-05 08:21:14.4698 INFO Found Outlook key 
2019-09-05 08:21:14.4698 INFO Office version 16 detected 
2019-09-05 08:21:14.4698 INFO Outlook path reported as C:\Program Files (x86)\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2019-09-05 08:21:14.4698 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2019-09-05 08:21:51.6293 INFO Command Line Args:  
2019-09-05 08:21:51.6605 INFO Found 15.0 key 
2019-09-05 08:21:51.6605 INFO Found 16.0 key 
2019-09-05 08:21:51.6605 INFO Found ClickToRun key 
2019-09-05 08:21:51.6605 INFO Found Common key 
2019-09-05 08:21:51.6605 INFO Found Delivery key 
2019-09-05 08:21:51.6605 INFO Found Outlook key 
2019-09-05 08:21:51.6605 INFO Office version 16 detected 
2019-09-05 08:21:51.6605 INFO Outlook path reported as C:\Program Files (x86)\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2019-09-05 08:21:51.6605 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2019-09-05 08:26:23.3489 INFO Command Line Args: -s 
2019-09-05 08:26:23.3802 INFO Found 15.0 key 
2019-09-05 08:26:23.3802 INFO Found 16.0 key 
2019-09-05 08:26:23.3802 INFO Found ClickToRun key 
2019-09-05 08:26:23.3802 INFO Found Common key 
2019-09-05 08:26:23.3802 INFO Found Delivery key 
2019-09-05 08:26:23.3802 INFO Found Outlook key 
2019-09-05 08:26:23.3802 INFO Office version 16 detected 
2019-09-05 08:26:23.3802 INFO Outlook path reported as C:\Program Files (x86)\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2019-09-05 08:26:23.3802 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2019-09-05 08:26:40.0762 INFO Command Line Args:  
2019-09-05 08:26:40.1074 INFO Found 15.0 key 
2019-09-05 08:26:40.1074 INFO Found 16.0 key 
2019-09-05 08:26:40.1074 INFO Found ClickToRun key 
2019-09-05 08:26:40.1074 INFO Found Common key 
2019-09-05 08:26:40.1074 INFO Found Delivery key 
2019-09-05 08:26:40.1074 INFO Found Outlook key 
2019-09-05 08:26:40.1074 INFO Office version 16 detected 
2019-09-05 08:26:40.1074 INFO Outlook path reported as C:\Program Files (x86)\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2019-09-05 08:26:40.1074 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2019-09-05 08:29:18.9831 INFO Command Line Args:  
2019-09-05 08:29:19.0160 INFO Found 15.0 key 
2019-09-05 08:29:19.0160 INFO Found 16.0 key 
2019-09-05 08:29:19.0160 INFO Found ClickToRun key 
2019-09-05 08:29:19.0160 INFO Found Common key 
2019-09-05 08:29:19.0160 INFO Found Delivery key 
2019-09-05 08:29:19.0160 INFO Found Outlook key 
2019-09-05 08:29:19.0160 INFO Office version 16 detected 
2019-09-05 08:29:19.0160 INFO Outlook path reported as C:\Program Files (x86)\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2019-09-05 08:29:19.0160 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)

**Comment by mscrivo** [comment]
Can you please try the latest version from here: https://github.com/mscrivo/OotD/releases/download/4.0.152/ootd-4.0.152.0.exe and tell me if it works any better?
