### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by mrappholz** [mscrivo/OotD#151]
**Describe the bug**
---------------------------
Outlook on the Desktop Error
---------------------------
There was an error initializing the application:

Ausnahmefehler aufgetreten. (0x80020009 (DISP_E_EXCEPTION))
---------------------------
OK   
---------------------------

**Windows Version**
Windows 10 x64 1909)

**Additional context and log file**
2020-08-26 06:39:32.5838 INFO Command Line Args:  
2020-08-26 06:39:32.6357 INFO Found 14.0 key 
2020-08-26 06:39:32.6357 INFO Found 15.0 key 
2020-08-26 06:39:32.6357 INFO Found 16.0 key 
2020-08-26 06:39:32.6357 INFO Found ClickToRun key 
2020-08-26 06:39:32.6357 INFO Found Common key 
2020-08-26 06:39:32.6357 INFO Found Delivery key 
2020-08-26 06:39:32.6357 INFO Found Excel key 
2020-08-26 06:39:32.6357 INFO Found MS Project key 
2020-08-26 06:39:32.6463 INFO Found Outlook key 
2020-08-26 06:39:32.6463 INFO Found PowerPoint key 
2020-08-26 06:39:32.6463 INFO Found Word key 
2020-08-26 06:39:32.6463 INFO Office version 16 detected 
2020-08-26 06:39:32.6463 INFO Outlook path reported as C:\Program Files\Microsoft Office\Root\Office16\ and Outlook.exe found in that path 
2020-08-26 06:39:32.6463 INFO Outlook Bitness is: x64 
2020-08-26 06:39:33.3415 DEBUG Checking to see if there is an instance running. 
2020-08-26 06:39:42.9804 INFO Starting the instance manager and loading instances. 
2020-08-26 06:39:43.1354 DEBUG Loading app settings from registry 
2020-08-26 06:39:43.1354 DEBUG Settings Found. 
2020-08-26 06:39:43.1354 DEBUG Multiple instances to load 
2020-08-26 06:39:43.2132 DEBUG Instantiating instance Aufgaben 
2020-08-26 06:39:45.1806 INFO Outlook folder path: IPM.Task 
2020-08-26 06:39:45.4783 ERROR Error initializing window. COMException System.Runtime.InteropServices.COMException (0x80020009): Ausnahmefehler aufgetreten. (0x80020009 (DISP_E_EXCEPTION))
   at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName) Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName)
2020-08-26 06:40:16.7413 ERROR Could not load instances COMException System.Runtime.InteropServices.COMException (0x80020009): Ausnahmefehler aufgetreten. (0x80020009 (DISP_E_EXCEPTION))
   at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName)
   at OotD.Forms.InstanceManager.LoadInstances()
   at OotD.Startup.Main(String[] args) Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName)
   at OotD.Forms.InstanceManager.LoadInstances()
   at OotD.Startup.Main(String[] args)

**Comment by GlitchyPie** [comment]
Started getting the same error after running "Outlook /cleanviews" because I was originally getting the "Could not read the Calendar" 

>2020-09-11 15:19:19.6578 ERROR Error initializing window. COMException System.Runtime.InteropServices.COMException (0x80020009): Exception occurred. (0x80020009 (DISP_E_EXCEPTION))
>   at OLXLib.IViewCtl.set_Folder(String pVal)
>   at AxOLXLib.AxViewCtl.set_Folder(String value)
>   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
>   at OotD.Forms.MainForm.LoadSettings()
>   at OotD.Forms.MainForm..ctor(String instanceName) Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
>   at AxOLXLib.AxViewCtl.set_Folder(String value)
>   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
>   at OotD.Forms.MainForm.LoadSettings()
>   at OotD.Forms.MainForm..ctor(String instanceName)
>2020-09-11 15:19:23.6468 ERROR Could not load instances COMException System.Runtime.InteropServices.COMException (0x80020009): Exception occurred. (0x80020009 (DISP_E_EXCEPTION))
>   at OLXLib.IViewCtl.set_Folder(String pVal)
>   at AxOLXLib.AxViewCtl.set_Folder(String value)
>   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
>   at OotD.Forms.MainForm.LoadSettings()
>   at OotD.Forms.MainForm..ctor(String instanceName)
>   at OotD.Forms.InstanceManager.LoadInstances()
>   at OotD.Startup.Main(String[] args) Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
>   at AxOLXLib.AxViewCtl.set_Folder(String value)
>   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
>   at OotD.Forms.MainForm.LoadSettings()
>   at OotD.Forms.MainForm..ctor(String instanceName)
>   at OotD.Forms.InstanceManager.LoadInstances()
>   at OotD.Startup.Main(String[] args)`

Clearing the settings from the registry (Computer\HKEY_CURRENT_USER\SOFTWARE\SMR Computer Services\Outlook on the Desktop) fixed it for me.  But **now** I can't get a second instance to show a different calendar because whenever I select the calendar i get 
![Screenshot 2020-09-11 154841](https://user-images.githubusercontent.com/71139548/92939925-53db7200-f446-11ea-8717-cf7f0cbd1617.png)
