### ISSUE TITLE
OotD error after installing Win 10 Version 2004

### ISSUE THREAD

**Issue by sooslaca** [mscrivo/OotD#154]
Hi @mscrivo ,

Exactly the same thing like in #128 just for winver 2004  build 19041.572
"There was an error initializing the application: Exception ocurred. (Exception from HRESULT : 0x80020009 (DISP_E_EXCEPTION))"

Logs:
```
2020-10-13 23:51:32.6449 DEBUG Checking to see if there is an instance running. 
2020-10-13 23:51:33.0602 INFO Starting the instance manager and loading instances. 
2020-10-13 23:51:33.2098 DEBUG Loading app settings from registry 
2020-10-13 23:51:33.2098 DEBUG Settings Found. 
2020-10-13 23:51:33.4277 ERROR Error setting MAPI folder. COMException System.Runtime.InteropServices.COMException (0x8004011C): The information store could not be opened.
   at Microsoft.Office.Interop.Outlook._NameSpace.GetFolderFromID(String EntryIDFolder, Object EntryIDStore)
   at OotD.Forms.MainForm.SetMAPIFolder() Microsoft.Office.Interop.Outlook.MAPIFolder GetFolderFromID(System.String, System.Object)    at Microsoft.Office.Interop.Outlook._NameSpace.GetFolderFromID(String EntryIDFolder, Object EntryIDStore)
   at OotD.Forms.MainForm.SetMAPIFolder()
2020-10-13 23:51:33.4854 ERROR Error initializing window. COMException System.Runtime.InteropServices.COMException (0x80020009): Exception occurred. (0x80020009 (DISP_E_EXCEPTION))
   at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName) Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName)
2020-10-13 23:51:34.6099 ERROR Could not load instances COMException System.Runtime.InteropServices.COMException (0x80020009): Exception occurred. (0x80020009 (DISP_E_EXCEPTION))
   at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName)
   at OotD.Forms.InstanceManager.LoadInstances()
   at OotD.Startup.Main(String[] args) Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OotD.Forms.MainForm.InitializeViewsFromPreferences()
   at OotD.Forms.MainForm.LoadSettings()
   at OotD.Forms.MainForm..ctor(String instanceName)
   at OotD.Forms.InstanceManager.LoadInstances()
   at OotD.Startup.Main(String[] args)
```

Would you might be able to fix it?

Thanks in advance

**Comment by sooslaca** [comment]
Interesting. I reinstalled iCloud a OotD and it started to work. Exact steps were:
- Signed out of iCloud
- Removed iCloud
- Removed OotD
- Restart
- Install iCloud
- Sign in iCloud
- Outlook check iCloud calendar there
- Installed OotD
- Works
