### ISSUE TITLE
Unhandled Exception when rename instance

### ISSUE THREAD

**Issue by AlexejHirsch** [mscrivo/OotD#174]
Version: 4.0.267

If i try to rename an instance from the menu of the tray icon i got the following unhandled exception.

--------------------------------------------------------------------------------------------------------------

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Forms.InstanceManager.InstanceRenamedEventHandler(Object sender, InstanceRenamedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OotD.Forms.MainForm.OnInstanceRenamed(Object sender, InstanceRenamedEventArgs e)
   at OotD.Forms.MainForm.RenameInstanceMenu_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Private.CoreLib.dll.
----------------------------------------
OotD.x86
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.0.267.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/OotD.x86.dll.
----------------------------------------
System.Runtime
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Runtime.dll.
----------------------------------------
System.Threading
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Threading.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52301.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/System.Windows.Forms.dll.
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52301.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/System.Windows.Forms.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Collections.Specialized.dll.
----------------------------------------
CommandLine
    Assembly-Version: 2.8.0.0.
    Win32-Version: 2.8.0.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/CommandLine.dll.
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/netstandard.dll.
----------------------------------------
NLog
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.12.301.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/NLog.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.ComponentModel.TypeConverter.dll.
----------------------------------------
System.Console
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Console.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Text.Encoding.Extensions.dll.
----------------------------------------
System.Linq
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Linq.dll.
----------------------------------------
System.Collections
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Collections.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Xml.ReaderWriter.dll.
----------------------------------------
System.Private.Xml
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Private.Xml.dll.
----------------------------------------
System.Memory
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Memory.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Private.Uri.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.ComponentModel.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Net.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Net.Primitives.dll.
----------------------------------------
System.Data.Common
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Data.Common.dll.
----------------------------------------
System.Net.Mail
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Net.Mail.dll.
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.IO.FileSystem.Watcher.dll.
----------------------------------------
System.Net.Sockets
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Net.Sockets.dll.
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Linq.Expressions.dll.
----------------------------------------
System.ObjectModel
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.ObjectModel.dll.
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Threading.Overlapped.dll.
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Diagnostics.FileVersionInfo.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Threading.Thread.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/System.Drawing.Common.dll.
----------------------------------------
NetSparkle
    Assembly-Version: 1.0.22.0.
    Win32-Version: 4.0.267.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/NetSparkle.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 6.0.21.52301.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/Accessibility.dll.
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/System.Resources.Extensions.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52301.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/System.Drawing.dll.
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Numerics.Vectors.dll.
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/Microsoft.Win32.Registry.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/Microsoft.Win32.SystemEvents.dll.
----------------------------------------
AxInterop.Microsoft.Office.Interop.OutlookViewCtl
    Assembly-Version: 1.1.0.0.
    Win32-Version: 1.1.0.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/AxInterop.Microsoft.Office.Interop.OutlookViewCtl.dll.
----------------------------------------
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/mscorlib.dll.
----------------------------------------
OLXLib
    Assembly-Version: 1.1.0.0.
    Win32-Version: 1.1.0.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/OLXLib.dll.
----------------------------------------
MACTrackBarLib
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.0.267.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/MACTrackBarLib.dll.
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Collections.Concurrent.dll.
----------------------------------------
System.Runtime.Loader
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Runtime.Loader.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52301.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.0/de/System.Windows.Forms.resources.dll.
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Runtime.Serialization.Formatters.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Collections.NonGeneric.dll.
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly-Version: 2.9.2.0.
    Win32-Version: 2.9.2.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/Microsoft.Win32.TaskScheduler.dll.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Runtime.CompilerServices.Unsafe.dll.
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Threading.ThreadPool.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Reflection.Metadata.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.Collections.Immutable.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 6.0.21.52210.
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.0/System.dll.
----------------------------------------

************** JIT-Debuggen **************

**Comment by mscrivo** [comment]
Thanks for reporting @AlexejHirsch ... unfortunately, I am unable to reproduce, even with changing my regional/language settings to German. Does it happen every time?
