### ISSUE TITLE
Crash when Outlook is turned off

### ISSUE THREAD

**Issue by kristianrl** [mscrivo/ootd#31]
When I turn off Outlook, OOTD crashes. I would like to see an error box telling me to start Outlook instead.
This is low-priority.
`
```
************** Exception Text **************
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ContextMenuStrip'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.ToolStripDropDown.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Int32 x, Int32 y)
   at System.Windows.Forms.ContextMenuStrip.ShowInTaskbar(Int32 x, Int32 y)
   at System.Windows.Forms.NotifyIcon.ShowContextMenu()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.100.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookDesktop
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/OutlookDesktop.exe
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/NLog.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.91.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 14.0.0.0
    Win32 Version: 14.0.4760.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/14.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1506
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
NetSparkle
    Assembly Version: 1.0.22.0
    Win32 Version: 1.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/NetSparkle.DLL
----------------------------------------
AxInterop.Microsoft.Office.Interop.OutlookViewCtl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/AxInterop.Microsoft.Office.Interop.OutlookViewCtl.DLL
----------------------------------------
OLXLib
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/OLXLib.DLL
----------------------------------------
MACTrackBarLib
    Assembly Version: 1.0.5800.39995
    Win32 Version: 1.0.5800.39995
    CodeBase: file:///C:/Program%20Files%20(x86)/Outlook%20on%20the%20Desktop/MACTrackBarLib.DLL
----------------------------------------
Microsoft.Office.Interop.OutlookViewCtl
    Assembly Version: 14.0.0.0
    Win32 Version: 14.0.4760.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.OutlookViewCtl/14.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.OutlookViewCtl.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
```

**Comment by mscrivo** [comment]
You're closing the main Outlook program and then OotD crashes?  It shouldn't be doing that as OotD should be using it's own instance behind the scenes.  What version of Office are you using?

**Comment by kristianrl** [comment]
I'm using Outlook 2010.

When the main Outlook program is closed, I see a small Outlook icon with a purple gear in the system tray. When I right click and close that instance, OOTD crashes.

**Comment by mscrivo** [comment]
Oh yeah, OotD requires that to run.  If you close it, OotD can't talk to Outlook and hence crashes.  When you shut down OotD, that Outlook Icon should go away as well.
