### ISSUE TITLE
Got an error while open the ootd.. Please advise...

### ISSUE THREAD

**Issue by rajeshmuthu1986** [mscrivo/ootd#58]
I am using MS office 2007 (32 bit - Windows 7)

I got the below error while open the ootd and i was tried reinstall the outlook. but it's not working..

Also i tried to run ootd as Administrator. but no luck. Please help me....

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OutlookDesktop.Forms.InstanceManager.ShowHideAllInstances()
   at OutlookDesktop.Forms.InstanceManager.TrayIcon_MouseDoubleClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseDoubleClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookDesktop
    Assembly Version: 3.4.0.0
    Win32 Version: 3.4.0
    CodeBase: file:///C:/Program%20Files/Outlook%20on%20the%20Desktop/OutlookDesktop.exe
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.2.3.1371
    CodeBase: file:///C:/Program%20Files/Outlook%20on%20the%20Desktop/NLog.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.4518.1014
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.Office.Interop.Outlook/12.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.4518.1014
    CodeBase: file:///C:/Windows/assembly/GAC/office/12.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
NetSparkle
    Assembly Version: 1.0.22.0
    Win32 Version: 1.0.22
    CodeBase: file:///C:/Program%20Files/Outlook%20on%20the%20Desktop/NetSparkle.DLL
----------------------------------------
AxInterop.Microsoft.Office.Interop.OutlookViewCtl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/Outlook%20on%20the%20Desktop/AxInterop.Microsoft.Office.Interop.OutlookViewCtl.DLL
----------------------------------------
OLXLib
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/Outlook%20on%20the%20Desktop/OLXLib.DLL
----------------------------------------
MACTrackBarLib
    Assembly Version: 1.0.5932.37702
    Win32 Version: 1.0.5932.37702
    CodeBase: file:///C:/Program%20Files/Outlook%20on%20the%20Desktop/MACTrackBarLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Also please see below pasted from log file...

2016-11-29 13:15:48.4959 DEBUG Checking to see if there is an instance running. 
2016-11-29 13:15:48.5159 DEBUG Successfully read reg key: HKLM\Software\Microsoft\Office 
2016-11-29 13:15:48.5159 DEBUG Analyzing subkey '10.0' 
2016-11-29 13:15:48.5159 DEBUG Office Version: 10 Detected 
2016-11-29 13:15:48.5159 DEBUG Analyzing subkey '11.0' 
2016-11-29 13:15:48.5159 DEBUG Office Version: 11 Detected 
2016-11-29 13:15:48.5159 DEBUG Office Version: 11 Detected 
2016-11-29 13:15:48.5159 DEBUG Office 2003 or higher is installed, now checking for Outlook exe 
2016-11-29 13:15:48.5159 DEBUG Office path reported as: C:\Program Files\Microsoft Office\Office12\ 
2016-11-29 13:15:48.5259 DEBUG Checking for Outlook exe in: C:\Program Files\Microsoft Office\Office12\ 
2016-11-29 13:15:48.5259 DEBUG Outlook exe found.  We're all good. 
2016-11-29 13:15:48.6259 INFO Starting the instance manager and loading instances. 
2016-11-29 13:15:48.6859 DEBUG Loading app settings from registry 
2016-11-29 13:15:48.6859 DEBUG Settings Found. 
2016-11-29 13:15:48.7459 ERROR Error initializing main view: System.Runtime.InteropServices.COMException (0x80040154): Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.AxHost.CreateWithLicense(String license, Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstanceCore(Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstance()
   at System.Windows.Forms.AxHost.GetOcxCreate()
   at System.Windows.Forms.AxHost.TransitionUpTo(Int32 state)
   at System.Windows.Forms.AxHost.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.AxHost.EndInit()
   at OutlookDesktop.Forms.MainForm.InitializeComponent()
   at OutlookDesktop.Forms.MainForm..ctor(String instanceName) 
2016-11-29 13:15:49.7459 WARN Unable to go to today on calendar. InvalidActiveXStateException Method 'GoToToday' cannot be invoked at this time. Void GoToToday()    at AxOLXLib.AxViewCtl.GoToToday()
   at OutlookDesktop.Forms.MainForm.UpdateTimer_Tick(Object sender, EventArgs e)

**Comment by mscrivo** [comment]
Seems to be an issue with your Office installation.  You can try reinstalling it or upgrading to a new version of office.
