### ISSUE TITLE
Outlook on the desktop startup error

### ISSUE THREAD

**Issue by GiuseppeChillemi** [mscrivo/ootd#7]
Hi, we are using outlook on the desktop in our company since last year but we stopped because of errors during startup and because the project seem stopped.

Now you are back, one year later with new releases and we are very happy. Ootd is the best way to use outlook but we still have last year problems and we wish to restart using the software.

We use it on a Server 2008 R2 64 Bit, outlook 2010 32 bit. All users are in terminal server enviroment.

Here is the log file:

2015-07-31 18:01:56.1940 DEBUG Checking to see if there is an instance running. 
2015-07-31 18:01:57.8190 DEBUG Successfully read reg key: HKLM\Software\Microsoft\Office 
2015-07-31 18:01:57.8190 DEBUG Analyzing subkey '11.0' 
2015-07-31 18:01:57.8190 DEBUG Office Version: 11 
2015-07-31 18:01:57.8190 DEBUG Office 2003 or higher is installed, now checking for Outlook exe 
2015-07-31 18:01:57.8190 DEBUG Office path reported as: C:\Program Files (x86)\Microsoft Office\Office14\ 
2015-07-31 18:01:57.8190 DEBUG Checking for Outlook exe in: C:\Program Files (x86)\Microsoft Office\Office14\ 
2015-07-31 18:01:57.8190 DEBUG Outlook exe found. 
2015-07-31 18:02:05.6390 INFO Starting the instance manager and loading instances. 
2015-07-31 18:02:05.7980 DEBUG Loading app settings from registry 
2015-07-31 18:02:05.8430 DEBUG Settings Found. 
2015-07-31 18:02:05.8450 DEBUG Multiple instances to load 
2015-07-31 18:02:05.8450 DEBUG Instantiating instance Ammi 
2015-07-31 18:02:06.0480 ERROR Error setting MAPI folder. COMException System.Runtime.InteropServices.COMException (0x8004010F): Operazione non riuscita.
   at Microsoft.Office.Interop.Outlook.NameSpaceClass.GetFolderFromID(String EntryIDFolder, Object EntryIDStore)
   at OutlookDesktop.Forms.MainForm.SetMAPIFolder() Microsoft.Office.Interop.Outlook.MAPIFolder GetFolderFromID(System.String, System.Object)    at Microsoft.Office.Interop.Outlook.NameSpaceClass.GetFolderFromID(String EntryIDFolder, Object EntryIDStore)
   at OutlookDesktop.Forms.MainForm.SetMAPIFolder()
2015-07-31 18:02:06.1410 ERROR Error initializing window. COMException System.Runtime.InteropServices.COMException (0x80020009): Eccezione. (Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION))
   at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OutlookDesktop.Forms.MainForm.LoadSettings()
   at OutlookDesktop.Forms.MainForm..ctor(String instanceName) Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OutlookDesktop.Forms.MainForm.LoadSettings()
   at OutlookDesktop.Forms.MainForm..ctor(String instanceName)
2015-07-31 18:02:08.3420 ERROR Could not load instances COMException System.Runtime.InteropServices.COMException (0x80020009): Eccezione. (Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION))
   at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OutlookDesktop.Forms.MainForm.LoadSettings()
   at OutlookDesktop.Forms.MainForm..ctor(String instanceName)
   at OutlookDesktop.Forms.InstanceManager.LoadInstances()
   at OutlookDesktop.Startup.Main() Void set_Folder(System.String)    at OLXLib.IViewCtl.set_Folder(String pVal)
   at AxOLXLib.AxViewCtl.set_Folder(String value)
   at OutlookDesktop.Forms.MainForm.LoadSettings()
   at OutlookDesktop.Forms.MainForm..ctor(String instanceName)
   at OutlookDesktop.Forms.InstanceManager.LoadInstances()
   at OutlookDesktop.Startup.Main()

**Comment by mscrivo** [comment]
Project was never stopped, I work on it on the side, in my spare time, as time allows.   

Anyway, can you try running OotD as administrator and see if it works?  COMExceptions usually indicate a system level problem, or something wrong with Office itself.
