### ISSUE TITLE
unable to open 

### ISSUE THREAD

**Issue by mvsreekanth** [mscrivo/OotD#90]
2018-04-05 22:51:50.1145 INFO Command Line Args: -s 
2018-04-05 22:51:50.2355 INFO Found 11.0 key 
2018-04-05 22:51:50.2355 INFO Found 12.0 key 
2018-04-05 22:51:50.2355 INFO Found 15.0 key 
2018-04-05 22:51:50.2355 INFO Found 16.0 key 
2018-04-05 22:51:50.2355 INFO Found 8.0 key 
2018-04-05 22:51:50.2355 INFO Found 9.0 key 
2018-04-05 22:51:50.2355 INFO Found ClickToRun key 
2018-04-05 22:51:50.2355 INFO Found Common key 
2018-04-05 22:51:50.2355 INFO Found Delivery key 
2018-04-05 22:51:50.2355 INFO Found Excel key 
2018-04-05 22:51:50.2355 INFO Found InfoPath key 
2018-04-05 22:51:50.2355 INFO Found Outlook key 
2018-04-05 22:51:50.2355 INFO Found Word key 
2018-04-05 22:51:50.2355 INFO Office version 16 detected 
2018-04-05 22:51:50.2355 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office12\ and Outlook.exe found in that path 
2018-04-05 22:51:50.2355 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-05 22:51:50.2355 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:51:50.2485 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:51:50.2985 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2018-04-05 22:52:08.0615 INFO Command Line Args:  
2018-04-05 22:52:08.1255 INFO Found 11.0 key 
2018-04-05 22:52:08.1265 INFO Found 12.0 key 
2018-04-05 22:52:08.1265 INFO Found 15.0 key 
2018-04-05 22:52:08.1265 INFO Found 16.0 key 
2018-04-05 22:52:08.1265 INFO Found 8.0 key 
2018-04-05 22:52:08.1265 INFO Found 9.0 key 
2018-04-05 22:52:08.1265 INFO Found ClickToRun key 
2018-04-05 22:52:08.1265 INFO Found Common key 
2018-04-05 22:52:08.1265 INFO Found Delivery key 
2018-04-05 22:52:08.1265 INFO Found Excel key 
2018-04-05 22:52:08.1265 INFO Found InfoPath key 
2018-04-05 22:52:08.1265 INFO Found Outlook key 
2018-04-05 22:52:08.1265 INFO Found Word key 
2018-04-05 22:52:08.1265 INFO Office version 16 detected 
2018-04-05 22:52:08.1415 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office12\ and Outlook.exe found in that path 
2018-04-05 22:52:08.1415 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:08.1415 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:08.1415 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:08.1415 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2018-04-05 22:52:23.2603 INFO Command Line Args:  
2018-04-05 22:52:23.3554 INFO Found 11.0 key 
2018-04-05 22:52:23.3754 INFO Found 12.0 key 
2018-04-05 22:52:23.3754 INFO Found 15.0 key 
2018-04-05 22:52:23.3754 INFO Found 16.0 key 
2018-04-05 22:52:23.3754 INFO Found 8.0 key 
2018-04-05 22:52:23.3754 INFO Found 9.0 key 
2018-04-05 22:52:23.3834 INFO Found ClickToRun key 
2018-04-05 22:52:23.3834 INFO Found Common key 
2018-04-05 22:52:23.3834 INFO Found Delivery key 
2018-04-05 22:52:23.3834 INFO Found Excel key 
2018-04-05 22:52:23.3834 INFO Found InfoPath key 
2018-04-05 22:52:23.3834 INFO Found Outlook key 
2018-04-05 22:52:23.3834 INFO Found Word key 
2018-04-05 22:52:23.3834 INFO Office version 16 detected 
2018-04-05 22:52:23.3834 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office12\ and Outlook.exe found in that path 
2018-04-05 22:52:23.3834 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:23.3834 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:23.3834 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:23.3994 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2018-04-05 22:52:40.2023 INFO Command Line Args:  
2018-04-05 22:52:40.2443 INFO Found 11.0 key 
2018-04-05 22:52:40.2443 INFO Found 12.0 key 
2018-04-05 22:52:40.2443 INFO Found 15.0 key 
2018-04-05 22:52:40.2473 INFO Found 16.0 key 
2018-04-05 22:52:40.2473 INFO Found 8.0 key 
2018-04-05 22:52:40.2473 INFO Found 9.0 key 
2018-04-05 22:52:40.2473 INFO Found ClickToRun key 
2018-04-05 22:52:40.2473 INFO Found Common key 
2018-04-05 22:52:40.2473 INFO Found Delivery key 
2018-04-05 22:52:40.2473 INFO Found Excel key 
2018-04-05 22:52:40.2473 INFO Found InfoPath key 
2018-04-05 22:52:40.2473 INFO Found Outlook key 
2018-04-05 22:52:40.2473 INFO Found Word key 
2018-04-05 22:52:40.2473 INFO Office version 16 detected 
2018-04-05 22:52:40.2473 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office12\ and Outlook.exe found in that path 
2018-04-05 22:52:40.2473 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:40.2473 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:40.2473 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-05 22:52:40.2473 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)

**Comment by mscrivo** [comment]
You seem to have multiple Outlook installations and it's getting confused.  I would recommend removing all old versions of Office, then doing a full repair on the latest one you have installed.  That should fix this.
