### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by vranicnikola** [mscrivo/OotD#92]
2018-04-23 07:43:53.6534 INFO Command Line Args: -s 
2018-04-23 07:43:53.7159 INFO Found 11.0 key 
2018-04-23 07:43:53.7315 INFO Found 12.0 key 
2018-04-23 07:43:53.7315 INFO Found 14.0 key 
2018-04-23 07:43:53.7315 INFO Found 15.0 key 
2018-04-23 07:43:53.7315 INFO Found 16.0 key 
2018-04-23 07:43:53.7315 INFO Found 8.0 key 
2018-04-23 07:43:53.7315 INFO Found Common key 
2018-04-23 07:43:53.7315 INFO Found Delivery key 
2018-04-23 07:43:53.7315 INFO Found Excel key 
2018-04-23 07:43:53.7315 INFO Found InfoPath key 
2018-04-23 07:43:53.7315 INFO Found MS Project key 
2018-04-23 07:43:53.7315 INFO Found OneNote key 
2018-04-23 07:43:53.7315 INFO Found Outlook key 
2018-04-23 07:43:53.7315 INFO Found PowerPoint key 
2018-04-23 07:43:53.7315 INFO Found Visio key 
2018-04-23 07:43:53.7315 INFO Office version 16 detected 
2018-04-23 07:43:53.7315 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office15\ and Outlook.exe found in that path 
2018-04-23 07:43:53.7315 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-23 07:43:53.7315 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:43:53.7315 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:43:53.7472 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2018-04-23 07:44:00.4915 INFO Command Line Args:  
2018-04-23 07:44:00.5363 INFO Found 11.0 key 
2018-04-23 07:44:00.5363 INFO Found 12.0 key 
2018-04-23 07:44:00.5363 INFO Found 14.0 key 
2018-04-23 07:44:00.5363 INFO Found 15.0 key 
2018-04-23 07:44:00.5363 INFO Found 16.0 key 
2018-04-23 07:44:00.5363 INFO Found 8.0 key 
2018-04-23 07:44:00.5363 INFO Found Common key 
2018-04-23 07:44:00.5363 INFO Found Delivery key 
2018-04-23 07:44:00.5363 INFO Found Excel key 
2018-04-23 07:44:00.5363 INFO Found InfoPath key 
2018-04-23 07:44:00.5363 INFO Found MS Project key 
2018-04-23 07:44:00.5453 INFO Found OneNote key 
2018-04-23 07:44:00.5453 INFO Found Outlook key 
2018-04-23 07:44:00.5453 INFO Found PowerPoint key 
2018-04-23 07:44:00.5453 INFO Found Visio key 
2018-04-23 07:44:00.5453 INFO Office version 16 detected 
2018-04-23 07:44:00.5453 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office15\ and Outlook.exe found in that path 
2018-04-23 07:44:00.5453 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-23 07:44:00.5453 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:44:00.5453 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:44:00.5453 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2018-04-23 07:44:26.8316 INFO Command Line Args:  
2018-04-23 07:44:26.8629 INFO Found 11.0 key 
2018-04-23 07:44:26.8629 INFO Found 12.0 key 
2018-04-23 07:44:26.8629 INFO Found 14.0 key 
2018-04-23 07:44:26.8629 INFO Found 15.0 key 
2018-04-23 07:44:26.8629 INFO Found 16.0 key 
2018-04-23 07:44:26.8629 INFO Found 8.0 key 
2018-04-23 07:44:26.8629 INFO Found Common key 
2018-04-23 07:44:26.8629 INFO Found Delivery key 
2018-04-23 07:44:26.8629 INFO Found Excel key 
2018-04-23 07:44:26.8629 INFO Found InfoPath key 
2018-04-23 07:44:26.8629 INFO Found MS Project key 
2018-04-23 07:44:26.8629 INFO Found OneNote key 
2018-04-23 07:44:26.8629 INFO Found Outlook key 
2018-04-23 07:44:26.8629 INFO Found PowerPoint key 
2018-04-23 07:44:26.8629 INFO Found Visio key 
2018-04-23 07:44:26.8629 INFO Office version 16 detected 
2018-04-23 07:44:26.8629 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office15\ and Outlook.exe found in that path 
2018-04-23 07:44:26.8629 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-23 07:44:26.8629 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:44:26.8629 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:44:26.8785 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)
2018-04-23 07:48:40.2555 INFO Command Line Args:  
2018-04-23 07:48:40.2868 INFO Found 11.0 key 
2018-04-23 07:48:40.2868 INFO Found 12.0 key 
2018-04-23 07:48:40.2868 INFO Found 14.0 key 
2018-04-23 07:48:40.2868 INFO Found 15.0 key 
2018-04-23 07:48:40.2868 INFO Found 16.0 key 
2018-04-23 07:48:40.2868 INFO Found 8.0 key 
2018-04-23 07:48:40.2868 INFO Found Common key 
2018-04-23 07:48:40.2868 INFO Found Delivery key 
2018-04-23 07:48:40.2868 INFO Found Excel key 
2018-04-23 07:48:40.2868 INFO Found InfoPath key 
2018-04-23 07:48:40.2868 INFO Found MS Project key 
2018-04-23 07:48:40.2868 INFO Found OneNote key 
2018-04-23 07:48:40.2868 INFO Found Outlook key 
2018-04-23 07:48:40.2868 INFO Found PowerPoint key 
2018-04-23 07:48:40.2868 INFO Found Visio key 
2018-04-23 07:48:40.2868 INFO Office version 16 detected 
2018-04-23 07:48:40.2868 INFO Outlook path reported as C:\Program Files\Microsoft Office\Office15\ and Outlook.exe found in that path 
2018-04-23 07:48:40.2868 INFO Unable to find key SOFTWARE\Microsoft\Office\16.0\Outlook 
2018-04-23 07:48:40.3024 INFO Trying SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:48:40.3024 INFO Unable to find key SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Outlook 
2018-04-23 07:48:40.3024 ERROR Error starting child process. NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OotD.Program.Main(String[] args) Void Main(System.String[])    at OotD.Program.Main(String[] args)

**Comment by mscrivo** [comment]
Do you have multiple versions of Outlook installed by chance?
